### ISSUE TITLE
Constituency Explorer

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#13]
It could be really nice to evolve the [Leading party for each constituency](https://data.voteforpolicies.org.uk/constituencies/leading-parties) page into a Constituencies Explorer. This could allow users to toggle different maps (and possibly other visualisations) from a constituency perspective e.g.

- [Choropleth showing strength of policial parties across the UK](https://github.com/voteforpolicies/data-website/issues/20)
- Leading parties by issue in each constituency
- Show constituencies where `$party_name` is leading
- Show who's leading in the marginal constituencies (as defined by [50for15](http://50for15.com/))

Martin has started to work on UI ideas for the Constituencies Explorer.

Please add your thoughts on this thread!

**Comment by martininma** [comment]
Hi Guys

As promised here is a link to an annotated PDF for the CE, think it would work well and site with the design of the site well. Look forward to hearing your thoughts or if you want to go over any of it.

http://we.tl/CkrGl5JwAm

**Comment by simonplend** [comment]
Looking good! Some really nice ideas in there, @martininma. I reckon @ryanhyslop is the best person to discuss this with from a UX perspective.

@EddyLane Does this give you something to go on for developing the Constituency Explorer?

**Comment by EddyLane** [comment]
Hiya, couple qs:

Does the API support the design at the moment? And how does this work on mobile? I think that's one of the key places where the current map falls down.

-Eddy

**Comment by simonplend** [comment]
The only things in that design that the API doesn't currently support are:

- Leading party by issue for all constituencies
- Leading parties in the marginal constituencies

I'm planning to add those in tomorrow. The response data structure for those will effectively be the same as it is for the existing 'leading parties for all constituencies' endpoint.

I agree about mobile - zero work has been done on making the current map responsive and it would be great if we could tackle this with the Constituency Explorer.

Worth mentioning thar we need to track down Geo/TopoJSON for the UK that includes Northern Ireland as policies are being added for the NI parties next week.

**Comment by simonplend** [comment]
Completed by https://github.com/voteforpolicies/data-website/pull/50.
