### ISSUE TITLE
Choropleth showing strength of policial parties across the UK

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#20]
The gist of this is to explore if and where certain parties' policies are proving popular.

Obviously, the SNP and Plaid Cymru will be very localised but perhaps too are the other major parties.

A choropleth would highlight constituencies in which a party is relatively popular, regardless of whether or not they are the most popular party in that constituency.

\- @michaeljpeake

**Comment by simonplend** [comment]
This is being worked on by @michaeljpeake.

**Comment by michaeljpeake** [comment]
The gist of this is to explore if and where certain parties' policies are proving popular.

Obviously, the SNP and Plaid Cymru will be very localised but perhaps too are the other major parties.

A choropleth would highlight constituencies in which a party is relatively popular, regardless of whether or not they are the most popular party in that constituency.

**Comment by simonplend** [comment]
PR for this here: https://github.com/voteforpolicies/data-website/pull/21

**Comment by simonplend** [comment]
The required API endpoints now exist for this:

`GET /parties/{party_slug}/constituencies/results.json` - List votes count and percentage for a specific party in all constituencies

**Comment by simonplend** [comment]
Completed by https://github.com/voteforpolicies/data-website/pull/50.
