### ISSUE TITLE
Adding Sass 

### ISSUE THREAD

**Issue by ryanhyslop** [voteforpolicies/data-website#34]
Along side our efforts to make the JS more module and concise, the same goes for the CSS.

Assuming #5 all goes well we can look at introducing: https://github.com/jking90/docpad-plugin-nodesass

From then on theres a little bit of discussion on how we approach this.

The simplest is that we continue to include the latest dist frontend.css file from the main voteforpolicies website as we do now,which means we have access to all the styling it provides, and we just add a new (complied ) stylesheet for the data site.

To me this seems like the most straight forward way, the only down side is a lack of transparency around what styles are actually available from the voteforpolicies main style sheet.

This could be somewhat alleviated by exposing the style guide from the main VFP site on a subdomain, styleguide.voteforpolicies.org.uk for instance. It already gets built to a subdirectory on deployment so in theory its just a case of setting up a vhost for it I *think*, could chat with @EddyLane about it. A bit sensitive as it'll touch the main vfp server I guess.

**Comment by simonplend** [comment]
Like your ideas here. Great to see https://styleguide.voteforpolicies.org.uk/ up and running too!

Good to get this on everyone's radar, but not sure if there's much more to discuss until DocPad is in place (waiting to get Browserify in at the moment - hopefully tonight, then DocPad will go in tomorrow with any luck).

**Comment by simonplend** [comment]
PR for this here: https://github.com/voteforpolicies/data-website/pull/46

**Comment by simonplend** [comment]
Merged PR. Ready for release.
