### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#5]
Templating to remove code duplication e.g. header and footer, as well as to make the code base generally more pleasant to work.

Will try out [DocPad](https://docpad.org/).

**Comment by ryanhyslop** [comment]
Let me know how you get on with this Simon, in my view this is the biggest barrier to contributing.

An alternative which would fit nicely in a js/frontend sort of stack is http://assemble.io/. Would require a build step on deployment however rather than just serving the repo static.

**Comment by simonplend** [comment]
@ryanhyslop I agree about it being the biggest barrier at present.

I'm going to look at this over the Bank Holiday weekend, so will definitely evaluate Assemble alongside DocPad. Thanks!

**Comment by simonplend** [comment]
Got caught up with other things, but I've picked this up again - hoping to have a work in progress PR up for everyone to see tonight.
