### ISSUE TITLE
Country results: Add missing icon and CSS for Ulster Unionist Party

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#53]
See here: https://data.voteforpolicies.org.uk/countries/results#countries/northern-ireland

**Comment by ryanhyslop** [comment]
This can be sorted by copying the new assets over from the main site, I've got a spare 15 mins so should have a PR ready shortly

**Comment by simonplend** [comment]
@ryanhyslop Excellent, thanks! Related issue here: https://github.com/voteforpolicies/data-website/issues/54

**Comment by simonplend** [comment]
Resolved.
